Linked list
Dariant31/AlgoDat_Praktikum pull request #3
Opened 2020-06-01 19:49 UTC by hangnguyende

Bitte schaut euch meine Linked List an, vielen Dank!

2020-06-15 14:39 UTC, Dariant31 requested changes
![image](https://user-images.githubusercontent.com/19270700/84670646-acbe6b80-af26-11ea-8f75-dfb2711b4fbc.png)

es gibt noch fehler hier,
wenn mann ein multiset-unsorted linked list addieren will

2020-06-15 14:55 UTC, Dariant31 requested changes
And on insert MultiSetUnsorted Linked list,
when mann insert. kommt "operation Failed" aber es ist doch inserted

2020-06-15 14:56 UTC, Dariant31 commented
bitte nutzt die Main Program um die ganze linked list zu testen.
also probieren die main test durchlaufen lassen so oft bis du kein fehler gefunden für alle fälle

2020-06-15 15:14 UTC, hangnguyende commented
danke, ich schaue mir es an

2020-07-07 09:43 UTC, Dariant31 approved these changes

2020-07-09 09:14 UTC, merged